### ISSUE TITLE
Adding promPort to pollers section in harvest.conf

### ISSUE THREAD

**Issue by Matthias-Beck** [NetApp/harvest#80] opened 2021-05-28 13:21 UTC
**Is your feature request related to a problem? Please describe.**
We want to have only one exporter and define the ports for the prometheus exporter in the single pollers

**Describe the solution you'd like**
Add the parameter promPort to the Poller section.

**Additional context**
Example conf file
```yaml
  Exporters:
  harvest:
    exporter: prometheus
    addr: 0.0.0.0
    global_prefix: netapp_
    master: True

Defaults:
  collectors:
    - Zapi
    - ZapiPerf
  exporters:
    - harvest
  use_insecure_tls: true
  auth_style: basic_auth
  username: <user>
  password: <password>

Pollers:
  clusterA:
    datacenter: DC1
    addr: clusterA
    promPort: 25000
  clusterB:
    datacenter: DC2
    addr: clusterB
    promPort: 25001

**Comment by cgrinds** [comment] 2021-06-07 13:28
@Matthias-Beck this is an area we want to improve. Adding a `promPort` to the poller section is one option we've discussed. Another option is to use Prometheus's file sd option. There are some advantages to file sd. What do you think about the file service discovery option listed below? Would it help solve your scenario? Any preference between the two?

# File Service Discovery Configuration

This option tells Harvest to handle the port mappings. Let's look at an example.

```
Exporters:
  prometheus1:
    exporter: Prometheus
    addr: 0.0.0.0
    file_sd:
      harvest_addr: localhost

Pollers:
  cluster-01:
    exporters:
    - prometheus1
  cluster-02:
    exporters:
    - prometheus1
```

Both `cluster-01` and `cluster-02` export to `prometheus1`. The `prometheus1` exporter is using the file service discovery by adding a `file_sd` section.

When these pollers start, they will pick a random free port for their web endpoints. In addition, Harvest will create a `prometheus1-target.yml` file in the current directory that will need to be copied to your Prometheus machine. The Harvest created target file name follows this pattern `<name of Exporter>-target.yml`.

The advantages of file service discovery are:

1. you don't have to specify a unique set of ports among pollers
2. it's easier to update Prometheus's list of scrape targets since Harvest creates that mapping in the `prometheus1-target.yml' file.
   
The cons of this approach are:
1. you have to copy the `target.yml` file to Prometheus when it changes.

Here's what `prometheus1-target.yml` might contain in this example:

```
targets:
  - 'localhost:98453'
  - 'localhost:32187'
```

The target hostname (localhost) shown in the example above is taken from the value of `harvest_addr` specified in the `file_sd` section. If Prometheus and Harvest are running on different machines, update `harvest_addr` with the IP address or hostname of your Harvest machine.  

Subsequent runs of `bin/harvest` will reuse ports defined in any of the Harvest created `*-target.yml` files. Harvest will keep the `*-target.yml` files in sync with your `harvest.yml` config file. Whenever there are port conflicts, cluster additions or removals, the `*-target.yml` will be updated and you'll be asked to copy the file again.

**Comment by mamoep** [comment] 2021-06-10 07:53
+1 for File SD. Will be easy solution if Harvest and Prometheus run on the same machine. Running on different machines could be solved via NFS mount.

**Comment by florianmulatz** [comment] 2021-06-10 08:59
Is this process already implemented? My tests says "no" - no files get's generated

Cheers

**Comment by rahulguptajss** [comment] 2021-06-10 09:26
@florianmulatz This is currently under proposal phase.

**Comment by florianmulatz** [comment] 2021-06-10 09:27
> This is currently under proposal phase.

okay thx!

**Comment by cgrinds** [comment] 2021-06-10 12:00
@florianmulatz does the FileSD proposal address your pain points of configuring a large number of clusters? I think FileSD is a more generally useful approach than `promPort`, but want to make sure it's a good solution for you.

**Comment by florianmulatz** [comment] 2021-06-10 12:06
Hey - yeah it's an interesting choice for configuring a large number of clusters. I think both seems to be legit - I think the user should have the choice what to use (maybe with the use of an option in the config-file)

Cheers

**Comment by cgrinds** [comment] 2021-06-22 12:23
Please take a look at https://github.com/NetApp/harvest/issues/172 the code is in main, we're working on the final documentation but what's listed in the issue is enough to kick the tires.

I believe it's a better solution than the _File Service Discovery Configuration_ proposal above

**Comment by cgrinds** [comment] 2021-07-14 15:05
Closing this issue since #172 covers this case. Feel free to reopen if you disagree

**Closed by cgrinds** 2021-07-14 15:05 UTC
Labels: feature, priority/P1
