### ISSUE TITLE
Shelfs dashboards shows from shelf ID numbers

### ISSUE THREAD

**Issue by matejzero** [NetApp/harvest#192] opened 2021-06-18 11:24 UTC
**Describe the bug**

Shelf dashboard doesn't show correct shelf IDs. They are cut out because of auto decimal setting.

**Environment**
- Harvest version: harvest version 21.05.2-1 (commit ce091de) (build date 2021-06-14T20:31:09+0530) linux/amd64
- Command line arguments used: /opt/harvest/bin/harvest restart --config /opt/harvest/harvest.yml
- OS: CentOS 7
- Install method: yum
- ONTAP Version: 9.7
- Other:

**To Reproduce**

Open Shelf dashboard with more than one shelf attached.

**Expected behavior**

Shelfs should have IDs 1.0, 1.1, 1.2.

**Actual behavior**

Due to auto decimals option in Grafana, IDs are without or too many decimals: 1. 1.10, 1.20...

![Screenshot 2021-06-18 at 13 22 15](https://user-images.githubusercontent.com/4689252/122553655-3f14b600-d038-11eb-8d7c-a239d478b79f.png)

**Possible solution, workaround, fix**

Add override option to show values as JSON values.

![Screenshot 2021-06-18 at 13 23 38](https://user-images.githubusercontent.com/4689252/122553772-679cb000-d038-11eb-9ce0-83e6e3035f6a.png)
![Screenshot 2021-06-18 at 13 23 04](https://user-images.githubusercontent.com/4689252/122553785-6bc8cd80-d038-11eb-8dda-0067d59ba940.png)

**Comment by Hardikl** [comment] 2021-06-21 07:32
Added required override option for that column in shelf dashboard.

**Comment by rajeshl8** [comment] 2021-06-23 18:16
I still see issue is happening in the build 21.05.3.1. Hence reopening the issue.
![image](https://user-images.githubusercontent.com/5583674/123147801-7961c700-d42d-11eb-89d0-3030dacb1b82.png)

**Comment by rajeshl8** [comment] 2021-06-24 03:44
Sorry i missed importing the latest dashboards to grafana server. After importing the latest dashboards i see the issue is fixed. Hence moving to fixed state.

![image](https://user-images.githubusercontent.com/5583674/123199407-d46eda80-d47c-11eb-9b32-033c74b0d5a8.png)

**Closed by rajeshl8** 2021-06-24 03:44 UTC
Labels: bug, status/open
