### ISSUE TITLE
Qtree 7mode Template is not available in this repository

### ISSUE THREAD

**Issue by jmg011** [NetApp/harvest#766] opened 2021-12-30 17:39 UTC
Hi, I did not find qtree 7mode template. Should I build one myself with qtree-list api? Or there is one built already but this repository is not updated?

**Comment by Hardikl** [comment] 2022-01-03 08:09
Hi @jmg011 , we have implemented qtree template with quota custom plugin in last release 21.11 for cmode. For 7mode, it's not implemented yet.

**Comment by jmg011** [comment] 2022-01-04 17:13
@cgrinds Thank you. Is there a plan to add 7-mode plugin? Is there any ETA?

**Comment by cgrinds** [comment] 2022-01-04 18:50
Hi @jmg011, we'll take a look at the feasibility. There's no ETA at the moment. If you need it sooner perhaps you're interested in trying to contribute this feature?

**Comment by jmg011** [comment] 2022-01-07 21:04
@rahulguptajss This is awesome. You're fast. I was checking with my peer to see if he can help with some workaround on this. Great to know you have built this pretty quick. Is this change ready to be implemented in production?

**Comment by rahulguptajss** [comment] 2022-01-10 06:55
@jmg011 Yes, Thanks to @Hardikl for quick turnaround on this. This still need to go through QA. Though you can give this a try in a non-production environment with our nightly builds 
https://github.com/NetApp/harvest/releases/tag/nightly

**Comment by jmg011** [comment] 2022-01-13 18:22
@Hardikl - Thank you so much Hardik. Appreciate your help on this. We could save time to build the work around on this due to your quick efforts. I'm going to upgrade test env today as suggested by @rahulguptajss. 

By the way, we have seen some qtree_labels issue for cmode. I'm bringing up here just to understand if there is any known issue or bug. 

For example, we are seeing total ~40k timeseries for qtree_labels, but we are seeing >88k timeseries for qtree_disk_used and other qtree related metrics also have > timeseries compared to qtree_labels. That means some of the qtrees do not show up in qtree_labels. Should I file a bug report on this? Is there anything I can do from my side to do the further debugging?

**Comment by cgrinds** [comment] 2022-01-13 20:19
@jmg011, yes please open a new issue for the qtree discrepancy. Posting you logs would be helpful for triaging. Maybe you're hitting a timeout. We'll take a look

**Comment by jmg011** [comment] 2022-01-13 21:53
@Hardikl  @rahulguptajss - I installed the nightly build and it is failing for the **_7-mode_** **qtree.** 

{"level":"error","Poller":"7modetestfiler","collector":"Zapi:Qtree","stack":[{"func":"New","line":"35","source":"errors.go"},{"func":"(*AbstractCollector).Start.func1","line":"259","source":"collector.go"},{"func":"gopanic","line":"1038","source":"panic.go"},{"func":"panicmem","line":"221","source":"panic.go"},{"func":"sigpanic","line":"735","source":"signal_unix.go"},{"func":"(*Instance).IsExportable","line":"43","source":"instance.go"} 
.
.
."time":"2022-01-13T13:49:36-08:00","message":"Collector panicked runtime error: invalid memory address or nil pointer dereference"}

@cgrinds - Sure, thanks. I will open the issue for qtree_labels discrepancy.

**Comment by rahulguptajss** [comment] 2022-01-14 07:45
@jmg011 could you share full stacktrace. One's you have shared doesn;t seem to have full logs about error.

**Comment by cgrinds** [comment] 2022-01-14 15:04
Root caused this nil dereference to a recent improvement in quota plugin for 7mode. Fixed in https://github.com/NetApp/harvest/pull/782

@jmg011 this fix is included in the most recent nightly build. Feel free to give it a try. The issue is one of your qtree instances wasn't found, which is unexpected. We improved the logging to identify these and that will help us understand if there's a naming difference on your 7mode system.

**Comment by jmg011** [comment] 2022-01-14 19:27
Thank you @cgrinds @rahulguptajss 

I installed latest nightly 22.1.14. I do not see the error for qtree but I do not see the metrics either. I see below warning messages. 

{"level":"info","Poller":"7modetestfiler","collector":"Zapi:Qtree","caller":"goharvest2/cmd/poller/collector/helpers.go:122","time":"2022-01-14T11:13:16-08:00","message":"best-fit template [conf/zapi/7mode/8.6.0/qtree.yaml] for [8.2.5]"}
{"level":"warn","Poller":"7modetestfiler","collector":"ZapiPerf:Qtree","error":"no best-fit template found","template":"qtree.yaml","caller":"goharvest2/cmd/collectors/zapi/collector/zapi.go:107","time":"2022-01-14T11:13:22-08:00","message":"Unable to import template"}
{"level":"warn","Poller":"7modetestfiler","caller":"./poller.go:651","time":"2022-01-14T11:13:22-08:00","message":"init collector-object (ZapiPerf:Qtree): no best-fit template found"}
{"level":"info","Poller":"7modetestfiler","collector":"Zapi:Qtree","task":"instance","object":"Qtree","caller":"goharvest2/cmd/poller/collector/collector.go:329","time":"2022-01-14T11:13:24-08:00","message":"no instances of object on system, entering standby mode"}
{"level":"info","Poller":"7modetestfiler","collector":"Zapi:Qtree","task":"data","caller":"goharvest2/cmd/poller/collector/collector.go:355","time":"2022-01-14T11:13:25-08:00","message":"recovered from standby mode, back to normal schedule"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}

**Comment by rahulguptajss** [comment] 2022-01-17 08:34
Thanks @jmg011 , Could you share response of zapi **qtree-list** , **quota-report**

**Comment by Hardikl** [comment] 2022-01-17 08:39
> @Hardikl - Thank you so much Hardik. Appreciate your help on this. We could save time to build the work around on this due to your quick efforts. I'm going to upgrade test env today as suggested by @rahulguptajss.
> 
> By the way, we have seen some qtree_labels issue for cmode. I'm bringing up here just to understand if there is any known issue or bug.
> 
> For example, we are seeing total ~40k timeseries for qtree_labels, but we are seeing >88k timeseries for qtree_disk_used and other qtree related metrics also have > timeseries compared to qtree_labels. That means some of the qtrees do not show up in qtree_labels. Should I file a bug report on this? Is there anything I can do from my side to do the further debugging?

Thanks for the update @jmg011
The issue you are mentioning about the difference count between qtree_labels and qtree_disk_used, it's not a bug. 

The reason is: The space related metrics[disk_used, disk_limit, disk....., etc] and filecount related metrics[file_limit, file_used, file......., etc] are at quota level and not qtree level. We can create many number of quotas in qtree with different disk space and file limit. 

This behaviour is same as Harvest 1.6. https://github.com/NetApp/harvest/issues/522#issuecomment-931507203

**Just to note:** We do process tree quota only, not user and group quota. But still there are tree quotas where qtree is not provided because it's applied to whole volume level. And that's the reason quota related metrics count can be higher than qtree numbers.

**Comment by jmg011** [comment] 2022-01-18 20:25
@Hardikl - Thank you for explaining and making me understand. It makes sense. I will double check and let you know if I see anything differently. 
@rahulguptajss  - I'm sorry, I could not understand this part - _"Could_ you share response of zapi qtree-list , _quota-report"_ Would you elaborate on how to get this?

**Comment by rahulguptajss** [comment] 2022-01-19 05:40
@jmg011 You can run below harvest commands for this.

```
bin/zapi -p 7modepollername show data --api qtree-list
bin/zapi -p 7modepollername show data --api quota-report
```

**Comment by jmg011** [comment] 2022-01-19 19:57
@rahulguptajss - Ah! okay. I thought you needed something from the logs. I misunderstood. I have attached below two files:
[qtree-list.txt](https://github.com/NetApp/harvest/files/7900197/qtree-list.txt)
[quota-report.txt](https://github.com/NetApp/harvest/files/7900198/quota-report.txt)

**Comment by Hardikl** [comment] 2022-01-20 12:17
Thanks @jmg011 for the zapi response.

**Issue**
Found the root cause. 
- vserver name(vfiler) is not available as part of the qtree and quota zapi response(as per the attached file). 
- As vserver field is part of the instance key, appropriate qtree instances would not be generated with key as '{qtree}.{volume}.{vserver}'. 
- So, while fetching qtree instance in quota plugin with above key, it's not able to get any qtree instance and error out.

This is one records of qtree response:
```
       {
          "volume": "ctest_scratch1",
          "qtree": "scratch1_qt2",
          "id": 2,
          "oplocks": "enabled",
          "security-style": "ntfs",
          "status": "normal"
        },
```

And this is one record of quota response:
```
        {
          "quota-type": "tree",
          "quota-target": "/vol/ctest_scratch1/scratch1_qt2",
          "volume": "ctest_scratch1",
          "tree": "scratch1_qt2",
          "disk-used": 2952,
          "disk-limit": 102400,
          "soft-disk-limit": "-",
          "threshold": "-",
          "files-used": 25,
          "file-limit": "-",
          "soft-file-limit": "-"
        },
```

from the above logs: --> vserver name is empty in all the metrics 
```
{"level":"warn","Poller":"7modetestfiler","plugin":"Zapi:Qtree","tree":"qt1_scratch1","volume":"ctest_scratch1","vserver":"","caller":"goharvest2/cmd/collectors/zapi/plugins/quota/quota.go:191","time":"2022-01-14T11:13:25-08:00","message":"No instance matching tree.volume.vserver"}
```






**More detail from zapidoc:**
from qtree 7mode zapidoc:
- vfiler is not the compulsory field in qtree response. (optional field)
![image](https://user-images.githubusercontent.com/83282894/150335933-9f9765ea-47cf-49d6-8031-d4f11d81d75f.png)


from quota 7mode zapidoc:
- If vfilers are in use then only vfiler name would be in the quota response. (optional field)
![image](https://user-images.githubusercontent.com/83282894/150335998-083cb16e-d182-48d0-81ad-82f7c583297e.png)





We will discuss within team and will share more detail about handling this optional field vserver for qtree and quota for 7mode.

**Comment by jmg011** [comment] 2022-01-24 23:09
@Hardikl Thank you for looking into this. Will wait for your response.

**Comment by Hardikl** [comment] 2022-01-25 07:20
@jmg011 , Changes for handling the vfiler in 7mode in qtree/quota are done as part of the PR #797

**Comment by jmg011** [comment] 2022-01-27 15:02
@Hardikl  Awesome work. Thank you so much. Should I pull this change from the latest nightly release?

**Comment by rahulguptajss** [comment] 2022-01-27 17:23
@jmg011 Yes, this change is present in nightly release.

**Comment by Hardikl** [comment] 2022-01-28 14:22
Hi @jmg011, PR #807 solves the qtree instance key issue for quota in 7mode, this change is available in today's nightly release. Please pull the latest nightly.

**Comment by jmg011** [comment] 2022-01-28 17:58
@Hardikl - Thank you so much! I now see data for below qtree metrics on 7mode. Should we expect any data on qtree_total_ops, qtree_nfs_ops, qtree_cifs_ops, qtree_internal_ops metrics? (for now, our use case is covered, asking for my knowledge) 

We now have data for below metrics for 7-mode. 

qtree_disk_used{}
qtree_file_limit{}
qtree_id{}
qtree_soft_disk_limit{}
qtree_threshold{}
qtree_disk_limit{}
qtree_files_used{}
qtree_labels{}
qtree_soft_file_limit{}

**Comment by cgrinds** [comment] 2022-01-31 14:02
thank for the confirmation that you're all set @jmg011 nice job @Hardikl

To answer your question about qtree perf metrics, I believe those can be added with a new perf template. Can you open a new issue or pull request with those specifics and let's close this one out.

**Comment by jmg011** [comment] 2022-01-31 21:43
@cgrinds Sure thing. Let's close this one. 

@Hardikl - Thank you again for a quick turn around.

**Closed** 2022-02-01 14:10 UTC
Labels: feature, status/testme
