### ISSUE TITLE
Add support for StorageGrid metrics

### ISSUE THREAD

**Issue by chrishenzie** [NetApp/harvest#772] opened 2022-01-05 21:34 UTC
NetApp StorageGrid provides APIs for querying for Prometheus metrics, for example:
![unnamed](https://user-images.githubusercontent.com/3466879/148292481-6e07f4af-6784-43b1-96d8-6931fa2c2b59.png)

However, it looks like StorageGrid does not have a general `/metrics` endpoint that will return all Prometheus metrics (similar to what Harvest does) -- they have to be individually queried per metric-name.

It would be great if Harvest can be extended to support StorageGrid. It looks like what needs to be done is aggregate the existing Prometheus metrics stored on the StorageGrid device.

**Comment by ruanruijuan** [comment] 2022-01-05 22:06
Same as #170.

**Comment by cgrinds** [comment] 2022-01-10 18:58
Closing as a duplicate of #170 - @chrishenzie we'll take this closed PR as another vote for StorageGrid support in #170. Feel free to +1 or comment there

**Closed by cgrinds** 2022-01-10 18:58 UTC
Labels: feature
