### ISSUE TITLE
Cuts in the collection of metrics of some cluster

### ISSUE THREAD

**Issue by faguayot** [NetApp/harvest#2113] opened 2023-05-29 07:49 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Hello,
We have experienced cuts in the collection of metrics from some cluster for some time. I don't think that always happens in the same clusters and it something that I didn't find yet the pattern. This occurs during a period of time for one or some cluster in particular.

I've put in the poller box the cluster where I detected the problem now but as I said before I saw the same behavior previously in other clusters but in the past I thought the problem of the missing data could be related to a restart of the harvest service since the time in the graph  was lower.

Missing metrics for the **blue** line at the beginning (Poller name: **sces1p3_03**) and yellow line (Poller name: **sces1p2_03**) later.
![image](https://github.com/NetApp/harvest/assets/85484449/bedb23c0-8bc1-45f4-91cf-d55176ad1d31)

The last point for the blue line is 24th may at 12:38 and for the yellow line at 14:50 the same day. These pollers started to draw points again for the blue line on 25th may at 12:35 and for the yellow 26th may at 15:01.

### Configuration

```text
Tools:
    grafana_api_token: -REDACTED-
Exporters:
    prometheus:
        exporter: Prometheus
        addr: -REDACTED-
        master: True
        port_range: 12989-13010
    influx:
        exporter: InfluxDB
        url: '-REDACTED-'
        addr: '-REDACTED-'
        bucket: ''
        org: ''
        token: '-REDACTED-'
Defaults:
    client_timeout: 60
    auth_style: basic_auth
    username: -REDACTED-
    password: -REDACTED-
    use_insecure_tls: true
    log_max_bytes: 10000000
    log_max_files: 10
    prefer_zapi: yes
    collectors:
        - Zapi
        - ZapiPerf
        - Ems
        - Rest
        - RestPerf
    exporters:
        - prometheus
        - influx
Pollers:
    unix:
        datacenter: local
        addr: -REDACTED-
        collectors:
            - Unix
        exporters:
            - prometheus
    SCES3T000:
        datacenter: technical
        addr: -REDACTED-
        exporters:
            - prometheus
    sces1t0_01:
        datacenter: technical
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p1_03:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p2_03:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p3_03:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    SCES1P000:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p1_02:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p2_02:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p3_02:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    SCES1T200:
        datacenter: technical
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    SCES1P200:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p0_04:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p1_01:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p2_01:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces1p3_01:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    SCES3P200:
        datacenter: brs
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces2p0_01:
        datacenter: production
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
    sces4p0_01:
        datacenter: colocation
        addr: -REDACTED-
        exporters:
            - prometheus
            - influx
```

### Poller

sces1p2_03,sces1p3_03

### Version

harvest version 23.05.0-1 (commit 6f74c7a5) (build date 2023-05-03T08:08:46-0400) linux/amd64

### Poller logs

```text
I will send you the logs file to the email.
```

### OS and platform

Red Hat Enterprise Linux release 8.4 (Ootpa)

### ONTAP or StorageGRID version

NetApp Release 9.10.1P8

**Comment by faguayot** [comment] 2023-05-29 13:17
@rahulguptajss I've tried to attach again the files. Let me know if they are ok or you are still suffering the problem with the corruption.

**Comment by Hardikl** [comment] 2023-05-30 10:24
@faguayot 
Thanks for sharing the log files again. We have received them and did initial investigation. 
Found few errors:
1.  `duplicate instancekey error`, @rahulguptajss has created [issue](https://github.com/NetApp/harvest/issues/2114) for this and we will look into it.
```
{"level":"error","Poller":"sces1p3_03","plugin":"ZapiPerf:Volume","object":"Volume","error":"duplicate instance key => .","key":".","caller":"volume/volume.go:88","time":"2023-05-24T10:28:02+02:00","message":"Failed to create new instance"}
```

2.  `System busy errors`, These logs exist in both pollers and started to occur for poller xxxx_03_03 around 12:34(as you have mentioned). This logs are coming directly from ONTAP and Harvest show them as-is.
```
{"level":"info","Poller":"sces1p3_03","collector":"ZapiPerf:LIF","error":"API request rejected => System busy: 17 requests on table \"perf_object_get_instances\" have been pending for 2 seconds. The last completed call took 94 seconds.","task":"data","caller":"collector/collector.go:365","time":"2023-05-24T12:34:02+02:00","message":"API rejected, entering standby mode"}
{"level":"info","Poller":"sces1p3_03","collector":"ZapiPerf:NicCommon","error":"API request rejected => System busy: 17 requests on table \"perf_object_get_instances\" have been pending for 2 seconds. The last completed call took 94 seconds.","task":"data","caller":"collector/collector.go:365","time":"2023-05-24T12:34:02+02:00","message":"API rejected, entering standby mode"}
...
```

While searching `System busy errors` in ONTAP side, found this burt [1387773](https://burtweb-prd.eng.netapp.com/burt/burt-bin/start?burt-id=1387773&btn=view)(not sure it's accessible from outside) which has same error stack.

Sharing the description detail and Public Review mentioned in the burt:

**DESCRIPTION:**
```
When counter manager appears to be hung which usually manifests as a problem in 
terms of gathering perf data or polling perf objects, following kind of messages
from mgwd would help in ascertaining that the issue is indeed in counter manager
daemon:
>>Attempt to get cm object resource_headroom_cpu failed:System busy: 7 requests on
table "perf_object_get_instances" have been pending for 13510621 seconds. The
last completed call took 0 seconds.
```
**PR**
```
------------------------
%%% TITLE: Blocked object and transport threads hamper counter manager's functionality
%%% DESCRIPTION:
Performance NetApp Manageability SDK (NMSDK) requests appear to get blocked after 
hitting the storage controller with multiple performance NMSDKs. This blockage occurs 
because the transport threads indefinitely waits on a mutex which, on the other
hand, is held by a dead thread. 
%%% WORKAROUND:
To temporarily resolve the issue, restart of the counter manager daemon(CMD) process on 
each node.
%%% NOTES:
None
--------------
```
3. `NFSv4 related issues`, These logs exist in both pollers, Need to check if this is related to Counter Manager as mentioned above
```
{"level":"info","Poller":"sces1p3_03","collector":"ZapiPerf:NFSv42Node","error":"API request rejected => Object \"nfsv4_2:node\" was not found.","task":"counter","caller":"collector/collector.go:365","time":"2023-05-24T11:08:09+02:00","message":"API rejected, entering standby mode"}
{"level":"info","Poller":"sces1p3_03","collector":"ZapiPerf:NFSv42","error":"API request rejected => Object \"nfsv4_2\" was not found.","task":"counter","caller":"collector/collector.go:365","time":"2023-05-24T11:08:09+02:00","message":"API rejected, entering standby mode"}
```

**Comment by faguayot** [comment] 2023-06-01 14:09
Sure @Hardikl 
I will share the information using the email.

Thanks.

**Comment by faguayot** [comment] 2023-06-13 19:38
I catched a new moment where it was happening the issue in one cluster.
![image](https://github.com/NetApp/harvest/assets/85484449/5cd37698-cb20-44f5-9b39-c5f9cb28aa33)

**Comment by cgrinds** [comment] 2023-06-14 16:10
hi @faguayot if you have the logs for that poller, please email them to us so we can take a look.

Hardik did a nice job analyzing the last set of logs you sent and found a logging issue. Let me explain what the problem is and why it might be related to the gaps shown above.

The Harvest perf collector works like this:
1. Harvest asks ONTAP for the instances of a resource (e.g. Volume)
2. Harvest uses the results of 1) to ask ONTAP for the counters for those instances
3. Harvest uses the results of 2) to calculate deltas, rates, etc.

The problem Hardik found in your logs occurs between 1 and 2. The instance we collected at step 1 was deleted by the time we got to step 2. That means at step 2, Harvest asks ONTAP for the counters of an instance that no longer exists. ONTAP returns an empty record when that happens, and Harvest was noisier about logging this than it should be. Hardik is working on a fix for that.

Is is possible that some of the gaps you're seeing on this cluster are because there are creates/deletes? Depending on the dashboard and whether the panel(s) are using topk or not, I think instance deletions could manifest as a gap because, on the left side of the gap, the instance was included in the top5, then it was deleted, and on the right side of the gap, a new instance was picked for the top5.

**Comment by faguayot** [comment] 2023-06-15 15:37
Hello @cgrinds, 

It is great that you found the problem with the many information that you had to review. I understood your explanation chris, thanks for making really clear always. If I am right this issue is happening with every instance (Aggregate, Volume, Node, Lun,etc) that gather of performance metrics/counters, is it correct my affirmation?

I will wait until you have the fix to check if the behaviour it is happening again or not.
Thanks.

**Comment by cgrinds** [comment] 2023-06-16 13:14
Hi @faguayot

While @Hardikl works on a potential fix for this issue, can you [email](mailto:ng-harvest-files@netapp.com) the most recent logs for one of your pollers with gaps? 

Any idea if that cluster may have deletions during the time of the gaps? And yes, to your question, the instance removal logic is the same for all object types.

**Comment by faguayot** [comment] 2023-06-19 14:41
Hello @cgrinds 
I don't remember which cluster was this behaviour and I unknown during which period of time we have seen these cuts. Apologize but I didn't take note of this info. If I see the same behaviour in other times, I directly will share the logs and those info.
I don't know what are you refering about the deletions? Where?

Thanks.

**Comment by faguayot** [comment] 2023-06-21 07:32
Hi @cgrinds , 

I think that now I understood your questions about the deleted objects which are continuously gathering information from the cluster and you try to understand if during the cuts anybody could delete those objects. My answer is no, we manage the creating the volumes, lun and all the different objects in a ONTAP cluster, so we know when we are deleting but we don't know in the different upper levels of storage what people do if they are deleting information which are inside those objects or not.

I hope my clarification give you the information that you asked.

Thanks.

**Comment by cgrinds** [comment] 2023-06-27 12:16
Hi @faguayot Hardik's changes are in nightly. If you want to try these out before the next release, you can grab the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly).

Feel free to [email](mailto:ng-harvest-files@netapp.com) the most recent logs for any of your pollers with gaps.

**Comment by faguayot** [comment] 2023-06-27 14:42
Hello @cgrinds 

Yes, I will try to test tomorrow but I don't know when I will find the problems if I do again. 

Thanks for the warning.

**Comment by cgrinds** [comment] 2023-11-15 13:52
@faguayot any updates on this issue?

**Comment by faguayot** [comment] 2023-11-16 08:48
Hello  @cgrinds , 

I haven't seen the cuts during this time but I don't know if the problem disappeared with any release or if I didn't see. If you want we can close the issue and if it appear again then we will review.

Thanks.

**Closed** 2023-11-16 12:59 UTC
Labels: status/needs-triage, waiting-customer-response

**Comment by faguayot** [comment] 2024-04-19 06:47
Hello, 

Recently we are experiencing times in which we have cuts in the recollection of the data. These cuts was happened this night.

![image](https://github.com/NetApp/harvest/assets/85484449/784f5d10-c9df-4da6-9f2d-6f395c0199e4)

But I have catched other days in which this happens:

![image](https://github.com/NetApp/harvest/assets/85484449/e922b290-0d1e-40af-bf6e-f5b5b9a215e2)

I don't know if this could be related with the same issue that you deallt here or if it is something different.

**Comment by faguayot** [comment] 2024-04-19 12:38
The harvest version it's the latest available

`harvest version 24.02.0-1 (commit 8f9201cc) (build date 2024-02-21T10:01:19-0500) linux/amd64`

Refering to the logs, I have sent the logs from today because their are heavy.

**Comment by faguayot** [comment] 2024-04-22 06:24
@rahulguptajss I am focusing on the last time where I have found this cuts which is 19April around 4:28am to 4:36am aproximately. I have checked the rest of pollers and at that time we don't see any cuts in the recollection, so it seems there is only 1 poller with that problem. I will let you know which is the information of the poller by email.
The metrics were we have seen those cuts are:

- node_total_ops
- node_total_data
- node_total_latency
- node_avg_processor_busy

Additionally to the node I think there are other metrics missing in the Power dashboard. 

![image](https://github.com/NetApp/harvest/assets/85484449/f32fe7dd-44aa-4b49-96c9-707fd6338fe9)
Let me know if you need something else.

**Comment by faguayot** [comment] 2024-04-23 16:01
Hi, 
@rahulguptajss Thanks for the detailed analysis. We are having peformance issues in this poller so it makes sense what you said about load and response time.  

About the command that you share to try took some time to show the result: 
`storage shelf show` 

I have stopped the harvest for this poller in others installations that we have for avoid that overload since it is the unique tool accesing for the cluster in conjunction with the OCUM/Active IQ.

**Comment by faguayot** [comment] 2024-04-25 08:33
I didn't know this option and it sounds good. Could you share with me, how can I use? It is an option for all pollers or is configurable only for one? Because I was thinking it will be beneficial for all pollers in general.

**Comment by faguayot** [comment] 2024-04-25 12:48
Yes, we are installing harvest by RPM.
